---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-65
    driver:
      box: chef/centos-6.5
      network:
      - ["private_network", {ip: "192.168.33.100"}]
      customize:
        cpus: 1
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[yum]
      - recipe[elasticsearch::default]
    attributes:
